-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 30, 2012 at 05:49 AM
-- Server version: 5.5.16
-- PHP Version: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `db_json_android`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_content`
--

CREATE TABLE IF NOT EXISTS `tbl_content` (
  `id_content` int(11) NOT NULL AUTO_INCREMENT,
  `judul` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `waktu` varchar(50) NOT NULL,
  `tanggal` varchar(50) NOT NULL,
  `penulis` varchar(50) NOT NULL,
  PRIMARY KEY (`id_content`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=19 ;

--
-- Dumping data for table `tbl_content`
--

INSERT INTO `tbl_content` (`id_content`, `judul`, `content`, `waktu`, `tanggal`, `penulis`) VALUES
(1, '2011, Lembaga Pemerintah Sudah Harus Cicipi Open Source', '<p>Jakarta - Pemerintah kian memantapkan langkah untuk bermigrasi ke penggunaan software Open Source. Tahun 2011 dijadikan target titik baliknya. Pada saat itu, seluruh institusi pemerintah diharapkan sudah harus be legal, terutama berbasis Open Source.  Demikian dikatakan Kemal Prihatman, Asisten Deputi Urusan Pengembangan dan Pemanfaatan TI Ristek dalam jumpa pers yang berlangsung di gedung BPPT, Jakarta, Kamis (5/6/2009).<br /><br />Menurutnya, target ini merupakan bagian dari isi surat edaran dari Menteri Pemberdayaan Aparatur Negara pada 5 April lalu yang isinya mewajibkan seluruh lembaga pemerintah untuk menggunakan software legal di seluruh jajarannya.  "Namun kami dari Ristek dengan alasan efisiensi anggaran jelas menyarankan be legal dengan Open Source. Tak hanya sistem operasinya, tapi juga aplikasi pendukung lainnya," tegasnya.  Kemal memprediksi, jumlah komputer yang digunakan seluruh institusi pemerintah di seluruh Indonesia mencapai 800 ribu unit. Nah dari jumlah tersebut, ia tak berani memastikan bahwa seluruhnya sudah legal menggunakan software proprietary.<br /><br />"Mungkin sistem operasinya sudah legal tapi aplikasi yang lainnya belum," imbuhnya.  Ristek sendiri bersama dengan Asosiasi Open Source Indonesia (AOSI) pada tahun 2009 ini menargetkan akan membantu setidaknya 10 lembaga pemerintah untuk melakukan migrasi ke Open Source.  "Kami lakukan secara bertahap, saat ini kita sedang membantu Depdiknas dan Kementerian PAN," tandasnya.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(2, 'Siapa Jawara Open Source Indonesia?  ', '<p>Jakarta - Pemerintah, lewat Kementerian Pendayagunaan Aparatur Negara, telah meminta agar instansi pemerintah memanfaatkan piranti lunak Open Source pada 2011. Siapa yang paling jago? Akan terbukti dalam ajang bernama Indonesia Open Source Award (IOSA) 2010.  IOSA 2010 akan digelar di Hotel Bidakara, Jakarta, pada Rabu, 28 Juli 2010. <br /><br />Seperti dikutip detikINET dari keterangan yang diterima, Selasa (27/7/2010), ajang tersebut juga akan digunakan untuk memantau kesiapan institusi pemerintahan untuk beralih ke Open Source.  Acara tersebut diselenggarakan bersama-sama oleh Kementerian Komunikasi dan Informatika , Kementerian Riset dan Teknologi, Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi, Asosiasi Open Source Indonesia (AOSI), serta Komunitas Open Source.  Selain penganugerahan, acara itu juga akan menampilkan workshop dan seminar. <br /><br />Termasuk di dalamnya, workshop yang terkait industri kreatif seperti pemanfaatan GIMP dan Blender, maupun sistem operasi Android yang sedang naik daun.  Sedangkan Seminarnya akan membahas topik kreativitas dengan memanfaatkan Open Source. Pembicara seperti Nukman Luthfie, Kak Seto hingga Indra Utoyo akan hadir di seminar tersebut.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(3, 'Kenapa Menggunakan Framework PHP Lebih Baik Dari Coding Manual?', '<p>Framework php disini adalah software yang dibuat dengan menggunakan PHP, nah software ini akan mempu membuat aplikasi web lain berbasis software framewrok tadi. Jadi semakin stabil, banyak feature dan mudah dikembangkan maka aplikasi web yang digunakan juga semakin bagus dan berkualitas. Dengan menggunakan framework php, kita bisa menghemat banyak waktu, karena semua fungsi-fungsi untuk pembuatan web sudah tersedia dan kita tinggal menggunakannya saja. <br /><br />Jika ada upgrade versi, kita tinggal mengupdate mesin frameworknya saja tanpa perlu menulis ulang program. Dengan diupgrage, framework menjadi lebih baik, mungkin saja ada fitur baru yang akan membuat aplikasi anda berjalan lebih optimal. Bekerja dengan framework php juga lebih terstruktur karena ada konsep MVC (model, visual, controller) yang membuat aplikasi web bisa dikerjakan banyak orang. Jadi dengan adanya framework php, apa kita ndak perlu belajar web lagi?<br /><br />Wah salah dunk kalau kayak gitu. Framework php itu didesain dengan sangat rumit, didalammnya full OOP, jadi harus paham terlebih dahulu konsep OOP di php, bisa baca OOP PHP bag 1, Membuat Object pada OOP dan Deklarasi hak akses pada OOP juga Inheritance pada OOP. Nah untuk sampai tahap OOP, harus melalui dulu apa yang disebut dengan pemrograman struktural. Disini masih perlu ikut kuliah pemrograman web, ha ha. Tapi untuk kedepannya, lebih baik fokus dengan framework, jauhkan sedikit ego anda sebagai programmer yang harus pure memakai produk sendiri. <br /><br />CMS juga menjadi perhatian tersendiri, karena CMS saat ini banyak digunakan karena mudah dan gratis. Nah, jika bisa mengutak-atik CMS, tahu dalemanya maka anda memiliki barang yang sangat bagus dan menarik. Tidak perlu coding dari awal lagi. SEO (search engine optimization) juga harus diperhatikan, karena ini faktor yang penting (kan nggak lucu kalau web anda sudah dirancang sedemikian baik, tapi sepi pengunjung). Ketiganya itu saya tidak mempelajarinya di kampus, dan sekarang saya sudah lulus, sedihnya. Jadi sebagai wejangan (halah.. sok tuwa he he), jika ingin bersaing di dunia web atau perusahaan besar, lebih baik perhatikan ketika elemen penting diatas, karena saat ini saya baru menyadari betapa pentingnya ketiga tersebut.<br /><br />Nah, framework php yang saya gunakan adalah Codeigniter, karena ini framework pertama yang saya pelajari dan langsung jatuh cinta sama Codeigniter.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(4, 'Membelah Web Dengan PHP Function', 'Biasanya tidak lengkap mempelajari bahasa pemrograman tanpa mempelajari apa yang di sebut dengan function. pengertian dari function sendiri adalah sub program yang terpisah dan dapat digunakan secara berulang-ulang. ini pengertian saya sendiri kok, karena saya biasa menggunakan function, lebih untuk menyederhanakan pembangunan program.\r\n\r\nDalam PHP juga ada function, terus ada tidak procedure nya? perbedaan antara function dan procedure adalah nilai keluaran dan sub program tersebut. Misalkan jika sub program tersebut di lengkapi dengan return maka subprogram tersebut adalah function, karena mengembalikan sebuah nilai, sedangkan jika tidak mengembalikan apa-apa, artinya tidak ada keyword return maka subprogram tersebut adalah procedure. Ini hanya untuk membedakan kok, pekerjaan dilapangan akan berbeda-beda dan menuntut penggunaan yang bervariasi, contohnya adalah mesin blog paling populer sejagad, yaitu wordpress.\r\n\r\nkita akan membuat sebuah function sederhana dengan menggunakan function, saya hanya memberikan konsep dasar function saja, nanti bisa dikembangkan sesuai kebutuhan.\r\n\r\n function cetak(){\r\n\r\n  $str="Belajar PHP dengan function";\r\n\r\n  return $str;\r\n\r\n }\r\n\r\n ?>\r\n\r\nArtinya function tersebut akan mengembalikan nilai berupa string. Tidak ada paramater yang disertakan. Contoh diatas adalah function yang paling sederhana. Jika dibuat menjadi procedure cukup dihilangkan keyword return, ganti dengan perintah echo untuk mencetak, maka hal itu bisa disebut dengan procedure. Cara menggunakannya bagaimana ?\r\n\r\n cetak();\r\n cetak();\r\n cetak();\r\n\r\nSedangkan function dengan menggunakan parameter adalah sebagai berikut\r\n\r\n function tambah($a,$b){\r\n  return $a+$b;\r\n }\r\n\r\nUntuk menggunakannya bagaimana ? seperti dibawah ini\r\n\r\n echo tambah(10,90); // menghasilkan 100\r\n echo tambah(18,50); // menghasilkan 68\r\n\r\nArtinya penggunaan function akan menjadi lebih fleksibel, banyak kreasi sehingga aplikasi yang dibuat menjadi lebih mudah dan cepat. Function bisa diartikan sebuah proses, anda bisa menyatukan semua proses-proses dalam sistem website anda dalam sebuah file yang berisi semua function, dan munkin anda bisa membuat framework sendiri. Dalam Wordpress juga seperti itu kok. Jadi jika anda sempat, pelajari function, terlebih anda akan mempelajari OOP.\r\nsemoga membantu.', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(5, 'Acara Latihan Dasar Kepemimpinan (LDK) UKM Kamera dan Kloso', '<p>Kemarin, UKM Kamera dan Kloso mengadakan acara LDK yang pertama. Acara LDK dibagi menjadi 2 sessi, yaitu sessi yang pertama bertempat di ruangan aula STIKOM PGRI Banyuwangi dan sessi yang kedua diadakan di Taman Nasional Alas Purwo. Acara LDK sessi Pertama hanya diisi dengan pembekalan teori-teori dasar kehidupan berorganisasi. Dimulai pukul 9 pagi, yang dibuka oleh Ketua STIKOM PGRI Banyuwangi, Drs. Eko Listiwikono, MM. Dilanjutkan dengan sambutan dari perwakilan anggota BEM dan pembekalan teori dari Drs. Mohammad Dedi dan Hadiq, M.Kom. <br /><br />Acara pembekalan teori disambut antusias oleh peserta LDK. Dan acara LDK UKM sessi pertama berakhir pada pukul 1 siang.  1 minggu kemudian, LDK sessi kedua dilaksanankan. Kali ini agak sedikit berbeda, dimana pada acara LDK sessi pertama bertempat di kampus dan hanya diisi dengan pembekalan teori, pada LDK sessi kedua ini langsung diisi dengan praktek dari teori-yeori yang sudah di dapat pada LDK sessi pertama. Acara bersifat outdor, yang bertempat di Taman Nasional Alas Purwo.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(6, 'UKM Kloso : Workshop Virtual OS di Linux', '<p>Berawal dari keinginan dan atusias yang besar dalam bidang open source, UKM Kloso (Komunitas Linux Open Source) Sabtu kemarin mengadakan acara Workshop Virtual OS di Linux. Peserta masih terbatas, yaitu hanya 30 orang dan itupun semua merupakan kalangan mahasiswa. UKM Kloso ingin meihat seberapa besar minat mahasiswa STIKOM PGRI Banyuwangi dengan software open source terutama Linux. Dan ternyata, sudah banyak yang memakai OS Linux di laptop mereka masing-masing.<br /><br />Linux adalah salah satu sistem operasi open source yang sudah tidak diragukan lagi ketanguhan dan kestabilannya. Sifat pengembangannya yang open source, menjadikan Linux banyak dipakai dan dikembangkan oleh orang-orang di seluruh belahan dunia. Sehingga banyak muncul turunan-turunan Linux yang biasa disebut dengan distro. Pada workshop virtual OS ini, distro Linux yang digunakan ialah Ubuntu 10.04. Ubuntu merupakan distro yang paling populer dan mudah untuk dipelajari oleh pemula sekalipun.<br /><br /><img style="float: right; margin: 5px; border: 0pt none;" title="Workshop Linux" src="/web_stikom/media/image/imgthumb/714172788-cimg5753.jpg" alt="Workshop Linux" width="300" height="209" />Acara workshop diisi dengan sessi instalasi Ubuntu 10.04, pengenalan aplikasi-aplikasi pendukung di Linux, instalasi aplikasi VirtualBox, dan instalasi sistem operasi Windows di atas mesin yang berjalan dengan sistem operasi Linux. Pada sessi instalasi Compiz (desktop effect), cukup membuat para peserta workshop berdecak kagum dengan keindahan desktop effect yang menjadi daya tarik Linux. Ditambah dengan sessi instalasi Virtual OS, dimana 2 sistem operasi bahakan lebih dapat berjalan dalam waktu yang bersamaan pada 1 komputer.<br /><br />Diharapkan setelah acara workshop ini, para peserta bisa mulai untuk beralih menggunakan sistem operasi dan aplikasi open source yang tidak kalah dengan aplikasi berbayar. Sehingga bisa lebih mengurangi penggunaan aplikasi bajakan.<br /><br />Salam Open Source!!!</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(7, 'Mengembalikan Panel di Gnome Linux', '<p>Tahu lah ya kita sebagai pengguna Linux itu maunya terus bereksperiment dengan penampilan sehingga sering kali kita merubahnya kelewat ekstrim sehingga seringkali bentuknya sudah tidak dikenali lagi. Ini yang terjadi pada saya sewaktu saya bereksperimen dengan panel di Sabily 9.04 saya. <br /><br />Tapi rupanya saya tidak sengaja mendelete network launcher di panel :(  Nah Memang bisa saja saya mengkostum Panel Gnome seperti pernah saya tanyakan ke master linux, mas Andy MSE. Namun hasil dari pimpin my panel saya terlalu ekstrim sehingga saya sendiri tidak mengenali lagi ini Ubuntu atau apa? hehehehe. <br /><br />Akhirnya saya men-searching di embah google cara me restore Gnome Panel seperti sediakala layaknya baru diinstal. berikut caranya:</p>\n<ul style="list-style-type: disc;">\n<li> pertama: ke <strong>Applications &gt; Acessories &gt; Terminal</strong></li>\n<li>kedua: setelah masuk Terminal, ketik kode berikut      gconftool-2 &acirc;&euro;&ldquo;recursive-unset /apps/panel&nbsp;</li>\n<li>ketiga: Kita Restart GDM dengan cara ketik Ctrl+Alt+f1 ,f2, f3, etc hingga kita masuk CLI (command Line Interface) sepenuhnya &acirc;&euro;&brvbar;&nbsp;</li>\n<li>Keempat: setelah masuk CLI, ketik:      sudo /etc/init.d/gdm stop<br /><br />Kemudian :      sudo /etc/init.d/gdm start  Niscaya Gnome Panel kamu akan seperti sedia kala &acirc;&euro;&brvbar;</li>\n</ul>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(8, 'Pengumuman UAS Semester Ganjil 2010/2011 dan Perpanjangan Batas Akhir Pengumpulan Surat Kerja', '<p>Diberitahukan kepada semua Mahasiswa STIKOM PGRI, bahwa pelaksanaan Ujian Akhir Semester (UAS) semester Ganjil 2010/2011 akan dilaksanakan mulai tanggal 31 Januari 2011 s/d 10 Februari 2011. Demikian harap diperhatikan. dan juga diberitahukan kepada mahasiswa bahwa Batas Akhir Pengumpulan Berkas Surat Keterangan Yang Tadinya.<br /><br />Ditetapkan anggal 31 Januari Akan Diperpanjang 2 Minggu. Mahasiswa Masih Dapat Mengumpulkan Surat Keterangan Kerja Hingga Tanggal 19 Februari 2011. Database Di SIAKAD Akan Di-RESET Otomatis Ke Program Pagi Semua Kecuali Bagi Mahasiswa Yang Bekerja Dan Mengumpulkan Berkas Keterangan Kerja. Sehingga Kompensasi Bagi Yang Tidak Mengumpulkan Berkas Tersebut, Wajib Untuk Masuk Program Pagi Atau Mengajukan CUTI Kuliah. <br /><br />Peraturan Ini Berlaku Untuk Semua Mahasiswa. Mohon Pengumuman Ini Dapat Disosialisasikan Kesesama Mahasiswa. Terima Kasih. jadwal uas bisa di download di menu <a href="http://stikombanyuwangi.ac.id/index.php/web/data/11">download</a>.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(15, 'Install PHP, Apache, dan MySQL di Ubuntu', '<p>Instalasi PHP di Linux terutama di Xubuntu sangat berbeda dengan di Window$. Kalau di Window$ paket-paket PHP, MySQL, Apache, dan Phpmyadmin sudah menjadi satu, sehingga sangat mudah untuk melakukan instalasinya. Sedangkan di Linux PHP, MySQL, Apache, dan Phpmyadmin dijual terpisah, jadinya kita harus mengkonfigurasinya satu persatu. Walaupun sudah disediakan LAMP (Linux, Apache, MySQL, Phpmyadmin) untuk Linux yang mudah dalam hal instalasinya, namun LAMP masih kurang lengkap dalam hal ketersediaan paket-paketnya. Maka saya putuskan untuk menginstal satu persatu paket-paketnya. Berikut caranya :<br /><br />1. Pastikan laptop atau PC kalian terhubung ke internet, karena kita akan melakukan proses instalasi secara online.<br />2. Buka terminal, dan login sebagai root.3. Ketikkan perintah berikut untuk menginstall paket PHP :<br /><br /><strong>sudo apt-get install php5</strong><br /><br />4. Selanjutnya instalasi web server Apache<br /><br />&nbsp;&nbsp;&nbsp; <strong>sudo apt-get install apache2</strong><br /><br />5. Instalasi database server MySQL<br /><br />&nbsp;&nbsp;&nbsp; <strong>sudo apt-get install mysql-server</strong><br /><br />Pada proses diatas, kita akan diminta untuk mengisi password dan username untuk koneksi database MySQL<br />6. Dan yang terakhir, Instalasi MySQL untuk Apache<br /><br />&nbsp;&nbsp;&nbsp; &nbsp;<strong>sudo apt-get install libapache2-mod-auth-mysql</strong><br /><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sudo apt-get install php5-mysql</strong><br /><br />Coba lakukan tes, buka browser kesayangan kalian dan ketikkan http://localhost. Jika muncul teks &ldquo;It works&rdquo; artinya apache sudah berhasil diinstall.<br /><br />Jika kalian terbiasa dengan Phpmyadmin yang memudahkan dalam hal pengelolaan database, berikut cara instalasinya :<br /><br />1. Buka terminal, dan ketikkan perintah berikut :<br /><br />&nbsp;&nbsp;&nbsp; <strong>sudo apt-get install phpmyadmin</strong><br /><br />2. Tunggu hingga proses download selesai. Secara default, phpmyadmin belum terkoneksi dengan modul PHP. Sehingga kita harus mengeditnya terlebih dahulu. Ketikkan perintah berikut untuk melakukan chmod :<br /><br />&nbsp;&nbsp;&nbsp; <strong>chmod 777 -R /etc/apache2/</strong><br /><br />3. Kemudian edit file konfigurasi dari apache dengan editor kesayangan kalian, disini</p>\n<p>menggunakan gEdit, ketikkan perintah berikut :<br /><br />&nbsp;&nbsp;&nbsp; <strong>gedit /etc/apache2/apache2.conf</strong><br /><br />4. Sisipkan beberapa kata berikut pada baris akhir :<br /><br />&nbsp;&nbsp;&nbsp; <strong>Include /etc/phpmyadmin/apache.conf</strong><br /><br />5. Simpan dan tutup.<br /><br />Untuk melakukan uji coba, silahkan buka browser kesayangan kalian dan ketikkan http://localhost/phpmyadmin. Masukkan username dan password, dan selamat menggunakan phpmyadmin di Linux</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(16, 'Aria2, Download Manager Untuk Linux', '<p>Anda pengguna Linux yang kesulitan mencari download manager seperti IDM di windows? Setelah mencari kemana-mana akhirnya dapat juga sofware untuk gantiin IDM di Ubuntu, nama softwarenya aria2. Berikut cara menginstal aria2 secara online :<br /><br />1. Pastikan laptop atau PC kalian terhubung dengan internet.<br /><br />2. Buka Terminal, dan ketikkan perintah berikut :<br /><br />&nbsp;&nbsp;&nbsp; sudo apt-get install aria2<br /><br />3. Tunggu sampai proses download dan instalasi selesai.<br /><br />4. Jika proses download dan instalasi sudah selesai, mari kita coba untuk mendownload file dengan aria2 ini.<br /><br />5. Untuk mendownload file masuk ke Terminal, ketikkan perintah dengan format sebagai berikut :<br /><br />&nbsp;&nbsp;&nbsp; aria2c [URL DOWNLOAD]<br /><br />&nbsp;&nbsp;&nbsp; contoh :<br /><br />&nbsp;&nbsp;&nbsp; root@sumawijaya-laptop:/home/sumawijaya# aria2c http://dl2.foss-id.web.id/opensuse/distribution/11.2/iso/openSUSE-11.2-KDE4-LiveCD-i686.iso<br /><br />6. Jika koneksi terputus, file download tersebut bisa di-resume kembali dengan perintah yang sama. Dalam hal ini, ingat baik-baik URL DOWNLOAD filenya. Bila perlu disimpan :D .<br /><br />Terbukti dengan menggunakan aria2 ini speed download memang benar-benar akan &ldquo;ngebut&rdquo;. Tapi konsekuensinya koneksi yang lain akan menjadi lambat, karena semua bandwidth disedot oleh si aria2 ini. Selain itu, dari soal tampilan yang masih berbasiskan teks, kurang mengesankan memang. Tapi kalau speed download yang didapatkan memang bisa &ldquo;ngebut&rdquo; yang gak akan jadi masalah :D . Aria2 memang software yang ampuh untuk masalah download-mendownload. Semoga bermanfaat untuk teman-teman yang suka mendowload film atau yang lainnya :D .</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(17, 'Pelatihan Desain Grafis Tingkat SMTA Se-Banyuwangi', '<p>Pesatnya perkembangan teknologi saat ini, sudah masuk ke berbagai lini kehidupan. Tak terbatas oleh umur dan berbagai bidang pekerjaan. Dua faktor itulah yang menjadi tujuan diadakannya pelatihan desain grafis oleh UKM Kamera STIKOM PGRI Banyuwangi. Dimana peserta pelatihan desain grafis ini dari kalangan siswa-siswi SMTA se-Banyuwangi kota. Ada 16 sekolah yang mengirimkan perwakilan siswa-siswinya untuk mengikuti acara pelatihan desain grafis ini.<br /><br />Acara pelatihan ini berlangsung selama 10 hari atau 10 kali pertemuan. Pelatihan desain grafis ini dibuka oleh Kepala Dinas Pendidikan Pemuda dan Olahraga Kabupaten Banyuwangi, Drs. Sulihtiyono. Beliau menyambut gembira acara pelatihan desain grafis yang diadakan di STIKOM PGRI Banyuwangi ini. Beliau berharap, pelatihan-pelatihan serupa yang berhubungan dengan teknologi informasi bisa terus diadakan. Sehingga kedepannya, perkembangan teknologi informasi di Kabupaten Banyuwangi dapat lebih maju lagi.<br /><br /><img style="float: right; margin: 5px;" title="Penyerahan Buku ajar untuk peserta, Oleh Kepala Dinas Pendidikan Pemuda dan Olahraga &amp; Ketua STIKOM" src="/web_stikom/media/image/imgthumb/1000190661-_mg_7722.jpg" alt="Penyerahan Buku ajar untuk peserta, Oleh Kepala Dinas Pendidikan Pemuda dan Olahraga &amp; Ketua STIKOM" width="250" height="174" />Materi desain grafis dibawakan oleh anggota-anggota UKM Kamera, yang meliputi Adobe Photoshop dan Corel Draw. Kedua aplikasi pengolah gambar tersebut adalah aplikasi yang sering digunakan di dalam dunia desain grafis. Para peserta sangat antusias mengikuti acara pelatihan ini.<br /><br />Di hari terakhir acara pelatihan, para peserta ditugaskan untuk membuat sebuah hasil karya berupa poster yang bertemakan dengan lingkungan. Dimana hasil karya dari peserta tersebut akan dijadikan arsip sekaligus tolak ukur, yaitu seberapa besar penyerapan materi desain grafis yang sudah diajarkan selama pelatihan berlangsung.<br /><br />Untuk melihat foto-foto kegiatan selama pelatihan, silahkan mengunjungi <a href="/web_stikom/index.php/web/galeri/2">link berikut</a>.</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung'),
(18, 'Membuat Sendiri Link Share ke Sosial Network', '<p>Prinsip kerjanya, link yang akan kita buat ini mengambil/mengcopy URL artikel yang sedang kita baca. Disini saya memakai fungsi dari salah satu javascript, yaitu document.URL. Fungsinya yaw untuk mengcopy URL artikel yang sedang kita baca. Dan untungnya lagi, situs-situs jejaring sosial seperti Facebook, Twitter dan yang lainnya, telah menyediakan fasilitas khusus untuk berbagi link seperti ini. OK deh, sekarang kita coba untuk proses implementasinya :D .<br /><br />1. Tentukan dulu letak link share network yang kalian inginkan, biar lebih gampang kita letakkan aja di bawah judul artikel.<br /><br />2. Masuk ke menu Appearance &gt; Editor &gt; pada list file theme, klik single.php.<br /><br />3. Nah, muncul deh sedikit script PHP :D . Terus cari letak yang pas menurut kalian.<br /><br />4. Terus isikan syntax Javascript berikut :<br /><br />&lt;script language=&rdquo;javascript&rdquo;&gt;<br />&nbsp;&nbsp;&nbsp; document.write(&ldquo;&lt;a href=&rsquo;http://twitter.com/home/?status=&rdquo; + document.URL + &ldquo;&lsquo; target=&rsquo;_blank&rsquo;&gt;[ TWITTER ]&lt;/a&gt;<br />&nbsp;&nbsp;&nbsp; | &lt;a href=&rsquo;http://www.facebook.com/share.php?u=&rdquo; + document.URL + &ldquo;&lsquo; target=&rsquo;_blank&rsquo;&gt;[ FACEBOOK ]&lt;/a&gt;<br />&nbsp;&nbsp;&nbsp; &lt;/script&gt;<br /><br />5. Klik Update File.<br /><br />6. Setelah itu, coba masuk ke blog kalian. Dan pilih salah satu artikel. Jreenggg,,,link share social network sudah terpasang di blog kalian.<br /><br />7. Agar terlihat lebih maknyuuss, kalian bisa menambahkan icon dari masing-masing situs jejaring sosial tersebut. Atau ingin menambahkan link share ke situs jejaring sosial yang lainnya.<br /><br />Gimana??? Gampang kan membuat link share social network sendiri. OK deh, semoga catatan kecil yang saya buat ini bisa menginspirasi kalian untuk mengembangkannya lebih baik lagi.<br /><br />Happy Blogging, Keep Coding,,,,</p>', '20:11:16', '29 Maret 2012', 'Gede Lumbung');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
